### ISSUE TITLE
When enabled, standard autocomplete stops working

### ISSUE THREAD

**Issue by inelukipg** [Smile-SA/module-elasticsuite-cms-search#6]
When I enable this module the standard autocomplete stops working.
Sometimes it shows up, but not showing the same result as before.

**Comment by romainruaud** [comment]
Hello @inelukipg 

Please provide more details about which versions of modules and Magento you are using : 

- Magento version

- smile/elasticsuite version
- smile/module-elasticsuite-cms-search version

Many things could happen here : 

- this module may not be totally compatible with Magento 2.2 since it has not been internally validated on Magento 2.2.

- the autocomplete was revamped in smile/elasticsuite 2.3.6 so ensure you have the following set of modules : 
    - smile/elasticsuite ^2.3.6
    - smile/module-elasticsuite-cms-search ^2.1.1


Let me know,

regards

**Comment by inelukipg** [comment]
Hi,
Sorry! 

Magento 2.1.8
smile/elasticsuite version: 2.3.8
smile/module-elasticsuite-cms-search 2.1.1

**Comment by mtarld** [comment]
Hi ! 
I encountered this issue some month ago. It comes from a conflict between names of data providers of elastic suite module and elastic suite CMS module

I've created a pull request fixing it : https://github.com/Smile-SA/module-elasticsuite-cms-search/pull/9

**Comment by romainruaud** [comment]
Closing since the PR fixing it has been merged.
